backend:
  name: test-repo
media_folder: static/assets/png
collections:
  - name: toolkits
    label: Toolkits
    folder: netlify_cms/components
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }